# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-13 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user_agent', models.TextField(default=b'unknown')),
                ('ip', models.GenericIPAddressField()),
                ('tag', models.CharField(max_length=140)),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
